package main

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"strconv"
	"time"

	"github.com/nats-io/nats.go"
	"github.com/redis/go-redis/v9"
)

var ctx=context.Background()
type client struct { t Trial; name string; r *redis.Client; n *nats.Conn; js nats.JetStreamContext; sub *nats.Subscription }
func connect(t Trial,name string)(*client,error){c:=&client{t:t,name:name};if t.Engine=="redis"{c.r=redis.NewClient(&redis.Options{Addr:t.Host+":6379",PoolSize:1,MaxRetries:-1,ReadTimeout:5*time.Second,WriteTimeout:5*time.Second,Protocol:2});return c,c.r.Ping(ctx).Err()};var e error;c.n,e=nats.Connect("nats://"+t.Host+":4222",nats.Name(name),nats.NoReconnect(),nats.Timeout(5*time.Second));if e!=nil{return c,e};c.js,e=c.n.JetStream(nats.MaxWait(5*time.Second));return c,e}
func(c *client)close(){if c.r!=nil{c.r.Close()};if c.n!=nil{c.n.Close()}}
func(c *client)create(key string,delta time.Duration)error{if c.r!=nil{return c.r.XGroupCreateMkStream(ctx,key,"workers","0").Err()};storage:=nats.FileStorage;if c.t.Profile=="memory"{storage=nats.MemoryStorage};_,e:=c.js.AddStream(&nats.StreamConfig{Name:key,Subjects:[]string{key},Storage:storage,Replicas:1,Retention:nats.LimitsPolicy,MaxMsgs:-1,MaxBytes:-1,MaxAge:0});if e!=nil{return e};_,e=c.js.AddConsumer(key,&nats.ConsumerConfig{Durable:"workers",AckPolicy:nats.AckExplicitPolicy,AckWait:delta,MaxAckPending:131072,MaxWaiting:512,DeliverPolicy:nats.DeliverAllPolicy,ReplayPolicy:nats.ReplayInstantPolicy});return e}
func(c *client)remove(key string)error{if c.r!=nil{return c.r.Del(ctx,key).Err()};return c.js.DeleteStream(key)}
func(c *client)publish(key string,p []byte)error{if c.r!=nil{return c.r.XAdd(ctx,&redis.XAddArgs{Stream:key,Values:map[string]any{"p":p}}).Err()};_,e:=c.js.Publish(key,p);return e}
func(c *client)bind(key string)error{if c.r!=nil{return nil};var e error;c.sub,e=c.js.PullSubscribe(key,"workers",nats.Bind(key,"workers"));return e}
type message struct {id int64; data []byte; redisID string; nmsg *nats.Msg; requested,received int64; deliveries uint64}
func parseRedis(m redis.XMessage,start int64)(*message,error){p,ok:=m.Values["p"].(string);if !ok||len(p)!=512{return nil,fmt.Errorf("invalid Redis payload")};b:=[]byte(p);return &message{id:int64(binary.BigEndian.Uint64(b)),data:b,redisID:m.ID,requested:start,received:mono()},nil}
func(c *client)receive(key string,wait time.Duration)(*message,error){start:=mono();if c.r!=nil{v,e:=c.r.XReadGroup(ctx,&redis.XReadGroupArgs{Group:"workers",Consumer:c.name,Streams:[]string{key,">"},Count:1,Block:wait}).Result();if e!=nil{return nil,e};if len(v)!=1||len(v[0].Messages)!=1{return nil,redis.Nil};return parseRedis(v[0].Messages[0],start)};v,e:=c.sub.Fetch(1,nats.MaxWait(wait));if e!=nil{return nil,e};stamp:=mono();if len(v)!=1||len(v[0].Data)!=512{return nil,fmt.Errorf("invalid JetStream payload")};meta,e:=v[0].Metadata();if e!=nil{return nil,e};return &message{id:int64(binary.BigEndian.Uint64(v[0].Data)),data:v[0].Data,nmsg:v[0],requested:start,received:stamp,deliveries:meta.NumDelivered},nil}
func(c *client)claim(key string,delta time.Duration,mode string)(*message,error){start:=mono();if mode=="claim"{v,e:=c.r.Do(ctx,"XREADGROUP","GROUP","workers",c.name,"COUNT",1,"BLOCK",100,"CLAIM",delta.Milliseconds(),"STREAMS",key,">").Result();if e!=nil{return nil,e};streams,ok:=v.([]any);if !ok||len(streams)==0{return nil,redis.Nil};stream,ok:=streams[0].([]any);if !ok||len(stream)!=2{return nil,fmt.Errorf("invalid CLAIM stream reply")};entries,ok:=stream[1].([]any);if !ok||len(entries)==0{return nil,redis.Nil};entry,ok:=entries[0].([]any);if !ok||len(entry)!=4{return nil,fmt.Errorf("CLAIM reply is not four fields")};fields,ok:=entry[1].([]any);if !ok||len(fields)!=2||fields[0]!="p"{return nil,fmt.Errorf("invalid CLAIM payload fields")};m,e:=parseRedis(redis.XMessage{ID:fmt.Sprint(entry[0]),Values:map[string]any{"p":fields[1]}},start);return m,e};v,_,e:=c.r.XAutoClaim(ctx,&redis.XAutoClaimArgs{Stream:key,Group:"workers",Consumer:c.name,MinIdle:delta,Start:"0-0",Count:1}).Result();if e!=nil{return nil,e};if len(v)==0{return nil,redis.Nil};return parseRedis(v[0],start)}
func(c *client)ack(key string,m *message)error{if c.r!=nil{n,e:=c.r.XAck(ctx,key,"workers",m.redisID).Result();if e==nil&&n!=1{return fmt.Errorf("XACK count %d",n)};return e};return m.nmsg.AckSync(nats.AckWait(5*time.Second))}
func timeout(e error)bool{return errors.Is(e,redis.Nil)||errors.Is(e,nats.ErrTimeout)||errors.Is(e,context.DeadlineExceeded)}
func(c *client)inventory(key string)(map[string]any,error){if c.r!=nil{n,e:=c.r.XLen(ctx,key).Result();if e!=nil{return nil,e};p,e:=c.r.XPending(ctx,key,"workers").Result();if e!=nil{return nil,e};info,ie:=c.r.Info(ctx,"persistence").Result();return map[string]any{"stored":n,"pending":p.Count,"persistence":info,"info_error":fmt.Sprint(ie)},nil};s,e:=c.js.StreamInfo(key);if e!=nil{return nil,e};u,e:=c.js.ConsumerInfo(key,"workers");if e!=nil{return nil,e};return map[string]any{"stored":int64(s.State.Msgs),"pending":int64(u.NumAckPending),"stream_info":s,"consumer_info":u},nil}
func(c *client)readback(key string,n int64,expected func(int64)[]byte)(map[string]any,error){seen:=make([]bool,n);count:=int64(0);check:=func(p []byte)error{if len(p)!=512{return fmt.Errorf("readback length %d",len(p))};id:=int64(binary.BigEndian.Uint64(p));if id<0||id>=n||seen[id]{return fmt.Errorf("readback duplicate or unexpected ID %d",id)};if !bytes.Equal(p,expected(id)){return fmt.Errorf("readback payload mismatch %d",id)};seen[id]=true;count++;return nil};if c.r!=nil{cursor:="-";for{entries,e:=c.r.XRangeN(ctx,key,cursor,"+",2048).Result();if e!=nil{return nil,e};if len(entries)==0{break};for _,m:=range entries{v,ok:=m.Values["p"].(string);if !ok{return nil,fmt.Errorf("invalid readback field")};if e=check([]byte(v));e!=nil{return nil,e};cursor="("+m.ID}}}else{ // A separate pull consumer verifies all retained payloads outside timing.
		name:="verify";_,e:=c.js.AddConsumer(key,&nats.ConsumerConfig{Durable:name,AckPolicy:nats.AckAllPolicy,MaxAckPending:4096,DeliverPolicy:nats.DeliverAllPolicy,ReplayPolicy:nats.ReplayInstantPolicy});if e!=nil{return nil,e};sub,e:=c.js.PullSubscribe(key,name,nats.Bind(key,name));if e!=nil{return nil,e};defer sub.Unsubscribe();for count<n{remaining:=n-count;batch:=1024;if remaining<int64(batch){batch=int(remaining)};msgs,e:=sub.Fetch(batch,nats.MaxWait(30*time.Second));for _,m:=range msgs{if ce:=check(m.Data);ce!=nil{return nil,ce}};if e!=nil{return nil,e};if len(msgs)==0{return nil,fmt.Errorf("readback made no progress")};if e=msgs[len(msgs)-1].AckSync(nats.AckWait(30*time.Second));e!=nil{return nil,e}}
	};return map[string]any{"expected_ids":n,"readback_ids":count,"all_512_bytes_equal":count==n,"digest_scheme":"deterministic exact byte comparison","id_format":"big-endian uint64"},nil}
func number(v any)int64{switch n:=v.(type){case int64:return n;case int:return int64(n);case float64:return int64(n);default:i,_:=strconv.ParseInt(fmt.Sprint(v),10,64);return i}}
